# Generated by Django 3.0.7 on 2021-02-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Falsulty Code')),
                ('name', models.CharField(max_length=500, verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Falcuties',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ethnic Group')),
            ],
        ),
    ]
