# Generated by Django 3.0.7 on 2021-02-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210218_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='profile',
            name='YOB',
            field=models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015)], default=2021, verbose_name='Year of Birth'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Course Code')),
                ('name', models.CharField(max_length=255, verbose_name='Course taken')),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Faculty')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ForeignKey(blank=True, help_text='COurse taken', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Course'),
        ),
    ]
