# Generated by Django 3.0.7 on 2021-02-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210218_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='location',
        ),
    ]
