# Generated by Django 3.0.7 on 2021-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210219_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='County',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='YOB',
            new_name='yob',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='accomodation',
            field=models.CharField(blank=True, choices=[('Hostel', 'Hostels'), ('Rentals', 'Rentals')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('Part time', 'Part Time'), ('Rregular', 'Regular'), ('GSSP', 'GSSP'), ('PSSP', 'PSSP')], default=None, max_length=10),
        ),
    ]
