# Generated by Django 3.0.7 on 2021-02-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210219_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Faculty',
            new_name='faculty',
        ),
    ]
